#!/bin/bash

set -e

if [[ -z "$1" ]]; then
  echo "Usage: $0 OUTPUT_FILE"
  exit 1
fi

output="$1"
echo "====> $output"

echo -n >> $output
for window in 1K 4K 8K 32K 128K; do
  echo "-----> $window window"
  echo -n "${window}," &>> $output
  iperf -c 192.168.33.10 -t 30 -w $window --reportstyle c >> $output
  sleep 5
done
