#!/bin/bash

set -e

if [[ -z "$1" ]]; then
  echo "Usage: $0 OUTPUT_FILE"
  exit 1
fi

output="$1"
echo "====> $output"

echo -n >> $output
for bandwidth in 50k 1m 5m 10m 50m; do
  echo "-----> $bandwidth bandwidth"
  echo -n "$bandwidth," &>> $output
  iperf -c 192.168.33.10 -u -t 30 -b $bandwidth --reportstyle c >> $output
  sleep 1
done
