#!/bin/bash

set -e

if [[ -z "$1" ]]; then
  echo "Usage: $0 OUTPUT_FILE"
  exit 1
fi

output="$1"
echo "====> $output"

function ensure_prefix() {
  while read line; do
    echo "$1,$line" | cat -
  done
}

echo -n >> $output
for bandwidth in 50k 1m 5m 10m 50m; do
  echo "-----> $bandwidth bandwidth"
  iperf -c 192.168.0.10 -u -t 30 -b $bandwidth # --reportstyle c \
    # | ensure_prefix $bandwidth \
    # >> $output
  sleep 1
done
